### PR TITLE
chore: re-add some Binskim flags

### PR DESCRIPTION
**Pull request by rzhao271**

### CODE REVIEW

**Comment by deepak1556** [comment]
Depends on resolving the windows compilation failure for `microsoft/vscode`, but LGTM otherwise.

**Review by deepak1556 — APPROVED** [review]

**Comment by joaomoreno** [comment]
@rzhao271 Converted this to draft. I'm still working on the fallout from the previous PR, since bringing that over to VS Code [broke in unexpected ways](https://dev.azure.com/monacotools/Monaco/_build/results?buildId=202831&view=logs&j=306b2268-2a17-5e97-ab97-f41a26dc5206&t=58f04053-9d9d-5049-6d7b-611119e6f145).

Are you sure `/w34244` and `/w34267` are still needed, given I removed the `/W3` altogether?

**Comment by rzhao271** [comment]
Those flags re-enable the warnings suppressed by node-gyp.

Here's the S360 item this PR references https://msazure.visualstudio.com/One/_workitems/edit/17148797.

Here's more info on the /w flags. https://learn.microsoft.com/en-us/cpp/build/reference/compiler-option-warning-level?view=msvc-170. Another option is to use `/we` for these flags so they get marked as errors no matter the warning level of the compiler.

**Comment by rzhao271** [comment]
I'm also double-checking whether my changes break the pipeline:
Test branch in microsoft/vscode: https://github.com/microsoft/vscode/compare/main...rzhao271/vscode-policy-test
CI run: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=203143&view=results

**Review by joaomoreno — APPROVED** [review]

**Pull request merged**
